dist: trusty
language: cpp
script:
  - mkdir cmake
  - cd cmake
  - wget http://www.cmake.org/files/v3.4/cmake-3.4.1.tar.gz &> /dev/null
  - tar -xvzf cmake-3.4.1.tar.gz &> /dev/null
  - cd cmake-3.4.1/ 
  - ./configure  &> /dev/null
  - make &> /dev/null
  - ls -al bin/
  - cd ..
  - cmake-3.4.1/bin/cmake .
  # - cmake .
